project_name: fastapi-base # 项目名称
enable_auth: false
debug: false
encryption_key: "DjCJN9dz5SjSd1e7BBMvy2f9_XdVuqfJGY7CTVLoQBI="
server:
  host: $SERVER_HOST # 服务部署的主机IP
  port: 8150 # 服务端口
  workers: 1 # 服务器并发进程数
  limit_concurrency: 200 # 每个worker并发请求数上限
  limit_max_requests: # 每个worker重启前最大请求数，null表示不限制
log:
  #log_dir: /app/log
  rotate_when: MIDNIGHT # 日志轮转时机: S, M, H, D, MIDNIGHT, W
  backup_count: 30 # 日志文件保留个数
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: abc123
  database: test_db
db:
  echo: false # 是否打印SQL语句
  pool_size: 64 # 数据库连接池大小
  max_overflow: 128 # 连接池的溢出连接数
  slow_query_threshold: 2.0 # 慢查询的检查阈值（秒）
nacos:
  server_url: http://192.168.31.27:8848 # Nacos服务端地址
  auth_enabled: false # Nacos是否已启用鉴权
  username: nacos # 鉴权用户名
  password: nacos # 鉴权用户密码
  namespace_id: public # 命名空间ID
  group: DEFAULT_GROUP # 分组名称
  enable_service_register: false # 是否启用服务发现注册
  enable_config_sync: false # 是否启用配置管理同步
  sync_interval: 15 # 配置同步间隔（秒）
  heartbeat_interval: 10 # 服务发现注册心跳间隔（秒）
gateway:
  login_url: http://192.168.31.27:8080/auth/login # 网关登录地址
  service_url: http://192.168.31.27:8080/{service_name} # 经过网关的当前服务地址
redis:
  url: redis://:123456@127.0.0.1:6379
  db: 1
es:
  host: http://192.168.98.65:9200,http://192.168.98.66:9200
  user: elastic
  password: elastic
  timeout: 60
mongo:
  uri: mongodb://192.168.0.1:27017/?authSource=admin
  db: test_db
sentry:
  enabled: false # 是否启用Sentry故障上报和性能监控
  dsn: http://493b9d47e6bfd3141b86d82d81a64d98@192.168.98.82:9000/3 # 数据源名称，指向Sentry服务项目地址
  traces_sample_rate: 1 # 性能跟踪采样率
  profiles_sample_rate: 0.05 # 性能分析采样率
sw:
  enabled: false  # 是否启用SkyWalking应用性能监控探针
  agent_collector_backend_services: 192.168.98.83:11800 # SkyWalking OAP 服务器地址
  agent_log_reporter_active: true # 是否启用日志关联追踪功能
  agent_log_reporter_level: WARNING # 日志上报级别: INFO, WARNING, ERROR
  agent_meter_reporter_active: true # 是否启用性能指标(Metrics)上报