service_name: fastapi-base
port: 8150
environment: dev # dev, test, prod
enable_auth: false
uvicorn:
  workers: 2
  limit_concurrency: 500
  limit_max_requests: 10000 # 每个worker重启前最大请求数，null表示不限制
log:
  app_logfile: ./log/app.log
  server_logfile: ./log/server.log
  access_logfile: ./log/access.log
  task_logfile: ./log/task.log
  rotate_when: MIDNIGHT # S, M, H, D, MIDNIGHT, W
  backup_count: 30
mysql:
  host: 192.168.98.55
  port: 4000
  user: dataware_house_testUser
  password: IlGiUL2qcdqckoIzj6c4
  database: dataware_house_test
db:
  echo: false # 是否打印SQL语句
  pool_size: 64 # 数据库连接池大小
  max_overflow: 128 # 连接池的溢出连接数
  slow_query_threshold: 2.0 # 慢查询的检查阈值（秒）
gateway:
  login_url: http://192.168.31.27:8080/auth/login # 网关登录地址
  service_url: http://192.168.31.27:8080/{service_name} # 经过网关的当前服务地址
nacos:
  server_url: http://192.168.31.27:8848 # Nacos服务端地址
  auth_enabled: false # Nacos是否已启用鉴权
  username: content-review # 鉴权用户名
  password: content-review@cqvip # 鉴权用户密码
  namespace_id: public # 命名空间ID
  group: DEFAULT_GROUP # 分组名称
  enable_service_register: false # 是否启用服务发现注册
  enable_config_sync: false # 是否启用配置管理同步
redis:
  url: redis://:www.cqvip.com@192.168.31.163:6379
  db: 15
es:
  host: http://192.168.98.65:9200,http://192.168.98.66:9200,http://192.168.98.67:9200,http://192.168.98.68:9200,http://192.168.98.69:9200,http://192.168.98.70:9200,http://192.168.98.71:9200,http://192.168.98.72:9200
  user: read_user
  password: 3W.cqvip.com
  timeout: 60
sentry:
  enabled: false # 是否启用Sentry故障上报和性能监控
  dsn: http://493b9d47e6bfd3141b86d82d81a64d98@192.168.98.82:9000/3 # 数据源名称，指向Sentry服务项目地址
  traces_sample_rate: 0.01 # 性能跟踪采样率
  profiles_sample_rate: 0.05 # 性能分析采样率